version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "30080:30080"  # Expose frontend on port 30080

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "30081:30081"  # Expose backend on port 30081
    depends_on:
      - db

volumes:
  postgres_data: