version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"  # Expose backend on port 5000
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "80:80"  # Expose frontend on port 80

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: